# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 2.7
virtualenv:
    system_site_packages: true
before_install:
    # add NeuroDebvian repository
    - wget -O- http://neuro.debian.net/lists/precise.us-ca.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
    - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
    - sudo apt-get update
    - sudo apt-get install python-matplotlib python-nitime
install:
    - python setup.py install -q 
script:
    nosetests pyarbus
